# Generated by Django 4.0 on 2023-03-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsageMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('name', models.TextField()),
                ('snap_time', models.DateTimeField()),
                ('memory', models.TextField()),
                ('command', models.TextField()),
                ('cpu', models.TextField()),
                ('username', models.TextField()),
            ],
        ),
    ]
