# Generated by Django 4.0 on 2023-03-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagemonitor',
            name='snap_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
